[tools]
rust = { version = "stable", targets = ["aarch64-apple-darwin", "x86_64-apple-darwin"] }

[tasks.fmt]
run = "cargo fmt"

[tasks."fmt:check"]
run = "cargo fmt --check"

[tasks."build:aarch64"]
run = "cargo build --release --target aarch64-apple-darwin"

[tasks."build:x86"]
run = "cargo build --release --target x86_64-apple-darwin"
