name: PR CI
on:
  pull_request:
    branches:
      - master

env:
  CARGO_TERM_COLOR: always

jobs:
  check-quality:
    name: Check Quality
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v6

      - uses: jdx/mise-action@v2

      - name: Ensure formatting
        run: mise run fmt:check

      - name: Ensure code validity
        run: mise run build:aarch64
