name: Release

on:
  release:
    types: [published]

env:
  CARGO_TERM_COLOR: always

jobs:
  release-macos-universal:
    name: macos-universal
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - uses: jdx/mise-action@v2

      - name: Build aarch64
        run: mise run build:aarch64

      - name: Build x86
        run: mise run build:x86

      - run: mkdir -p target/universal/release

      - name: Combine Binaries into Universal Binary
        run: >
          lipo -create -output
          "target/universal/release/nanoproxy"
          "target/x86_64-apple-darwin/release/nanoproxy"
          "target/aarch64-apple-darwin/release/nanoproxy"

      - name: Make universal zip
        run: |
          mkdir nanoproxy-macos-universal
          cp target/universal/release/nanoproxy nanoproxy-macos-universal
          zip -r nanoproxy-macos-universal.zip nanoproxy-macos-universal

      - name: Make SHA256 checksum
        run: shasum -a 256 nanoproxy-macos-universal.zip > nanoproxy-macos-universal.zip.sha256sum

      - name: Upload assets to Release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release upload "${{ github.ref_name }}" \
            nanoproxy-macos-universal.zip \
            nanoproxy-macos-universal.zip.sha256sum \
            --clobber
